import { type NextPage } from "next";
import Head from "next/head";
import Laptop from "../components/Laptop";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen w-full">
        <Laptop />
      </div>
    </>
  );
};

export default Home;
